import type * as THREE from "three";
import type { ChunkMeshData, ChunkMeta, IChunkStreamer } from "../../contracts/chunks";
import type { ProfilerHook } from "../../contracts/profiler";
import type { TerrainGenerator } from "../generation/TerrainGenerator";
import type { ChunkGenerator } from "../generation/ChunkGenerator";
import type { ChunkMeshBuilder } from "../chunks/ChunkMeshBuilder";
import type { ChunkPersistence } from "../chunks/ChunkPersistence";
import type { ChunkWorkerPool } from "../workers/ChunkWorkerPool";
import type { PerfProfileName } from "../perf/PerfProfile";

type Chunk = {
  mesh: THREE.Mesh;
};

export type ChunkManagerState = {
  perfProfileName: PerfProfileName;
  scene: THREE.Scene;
  chunkSize: number;
  chunkHeight: number;
  chunks: Map<string, Chunk>;
  chunksData: Map<string, Uint8Array>;
  chunksMeta: Map<string, ChunkMeta>;
  dirtyChunks: Set<string>;
  inFlightChunks: Map<string, Promise<void>>;
  lastCleanupAt: number;
  cleanupIntervalMs: number;
  runtimeGenBudgetMs: number;
  runtimeRebuildBudgetMs: number;
  runtimeRebuildMax: number;
  runtimeMeshFinalizeBudgetMs: number;
  runtimeMeshFinalizeMaxPerTick: number;
  runtimeMaxEnsuresActive: number;
  runtimeMaxEnsuresIdle: number;
  pendingChunks: Array<{ cx: number; cz: number; enqueuedAt: number }>;
  pendingSet: Set<string>;
  pendingMeshBuilds: Array<{
    cx: number;
    cz: number;
    meshData: ChunkMeshData;
    enqueuedAt: number;
  }>;
  desiredChunks: Set<string>;
  queueContext: { playerX: number; playerZ: number; viewX: number; viewZ: number } | null;
  queueNearLatencyMs: number;
  nearLatencyTargetMs: number;
  adaptiveBurstEnabled: boolean;
  adaptiveBurstActive: boolean;
  burstHoldUntilMs: number;
  burstCooldownUntilMs: number;
  frameP99Ms: number;
  burstEnterCount: number;
  burstExitCount: number;
  burstEnterNearLatencyMs: number;
  burstExitNearLatencyMs: number;
  burstEnterFrameP95Ms: number;
  burstExitFrameP95Ms: number;
  burstFrameP99HardCapMs: number;
  burstEnsuresActive: number;
  burstEnsuresIdle: number;
  burstMeshFinalizeBudgetMs: number;
  burstMeshFinalizeMaxPerTick: number;
  burstRebuildMaxPerTick: number;
  burstMinHoldMs: number;
  burstCooldownMs: number;
  queueForwardBias: number;
  maxPendingChunks: number;
  processingQueue: boolean;
  meshFinalizeProcessing: boolean;
  rebuildQueue: Array<{ cx: number; cz: number }>;
  rebuildSet: Set<string>;
  maxRebuildQueue: number;
  profiler: ProfilerHook | null;
  rebuildCountThisFrame: number;
  lastUpdateAt: number;
  frameSamples: number[];
  frameSampleSize: number;
  dynamicRadius: number;
  radiusMode: "dynamic" | "fixed";
  lastRadiusAdjustAt: number;
  radiusAdjustCooldownMs: number;
  radiusP95TargetMs: number;
  radiusStableMs: number;
  runtimeGenBudgetMinMs: number;
  runtimeGenBudgetMaxMs: number;
  runtimeGenBudgetStepMs: number;
  runtimeRebuildBudgetMinMs: number;
  runtimeRebuildBudgetMaxMs: number;
  runtimeRebuildBudgetStepMs: number;
  lastBudgetAdjustAt: number;
  budgetAdjustCooldownMs: number;
  lastPlayerPos: THREE.Vector3;
  lastPlayerAtMs: number;
  idleSinceMs: number;
  isIdle: boolean;
  idleSpeedThreshold: number;
  idleEnterDelayMs: number;
  idleExitSpeedMultiplier: number;
  idleRadiusDelta: number;
  idlePendingLimit: number;
  terrainGen: TerrainGenerator;
  chunkGenerator: ChunkGenerator;
  meshBuilder: ChunkMeshBuilder;
  persistence: ChunkPersistence;
  streamer: IChunkStreamer;
  workerPool?: ChunkWorkerPool;
  useWorkers: boolean;
  useWorkerMesh: boolean;
};
